debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

#[entryPoints]
#  [entryPoints.http]
#  address = ":80"
#    [entryPoints.http.redirect]
#    entryPoint = "https"
#  [entryPoints.https]
#  address = ":443"
#  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
#domain = "my-awesome-app.org"
watch = true
exposedByDefault = false

# [acme]
# email = "your-email-here@my-awesome-app.org"
# storage = "acme.json"
# entryPoint = "https"
# onHostRule = true
# [acme.httpChallenge]
# entryPoint = "http"

